<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>maximo.swg</groupId>
        <artifactId>javascriptctrl</artifactId>
        <version>1.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>application</artifactId>
    <name>Maximo Application</name>
    <description>UI and MBO for Maximo javascript control.</description>
    <packaging>pom</packaging>

    
    <build>
        <sourceDirectory>maximouiweb/src/</sourceDirectory>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <executions>
                    <execution>
                        <id>compile-businessobject</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <compileSourceRoots>
                                <compileSourceRoot>${project.basedir}/businessobjects/src</compileSourceRoot>
                            </compileSourceRoots>
                            <outputDirectory>${project.basedir}/businessobjects/classes</outputDirectory>
                            <includes>
                                <include>**/*.java</include>
                            </includes>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-maximouiweb</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <compileSourceRoots>
                                <compileSourceRoot>${project.basedir}/maximouiweb/src</compileSourceRoot>
                            </compileSourceRoots>
                            <outputDirectory>${project.basedir}/maximouiweb/webmodule/WEB-INF/classes</outputDirectory>
                            <includes>
                                <include>**/*.java</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.maximo.external</groupId>
            <artifactId>businessobjects</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/horfee/Developpement/maximo/wlp/usr/servers/MXServer/apps/maximouiweb.war/WEB-INF/lib/businessobjects1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.maximo.external</groupId>
            <artifactId>maximouiweb</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/horfee/Developpement/maximo/wlp/usr/servers/MXServer/apps/maximouiweb.war/WEB-INF/classes.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.maximo.external</groupId>
            <artifactId>json</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/horfee/Developpement/maximo/wlp/usr/servers/MXServer/apps/maximouiweb.war/WEB-INF/lib/json4j.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
