<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>maximo.swg</groupId>
        <artifactId>javascriptctrl</artifactId>
        <version>1.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>tools</artifactId>
    <name>Maximo Tools</name>
    <description>Tooling module for Maximo development.</description>
    <packaging>pom</packaging>


    <dependencies>
        <dependency>
            <groupId>com.maximo.external</groupId>
            <artifactId>businessobjects</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/horfee/Developpement/MaximoJavascriptComponent/maximo_libs/businessobjects.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.maximo.external</groupId>
            <artifactId>tools</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/horfee/Developpement/MaximoJavascriptComponent/maximo_libs/MaximoTools.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.maximo.external</groupId>
            <artifactId>jdom</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/horfee/Developpement/MaximoJavascriptComponent/maximo_libs/jdom.jar</systemPath>
        </dependency>
        <!-- Add module-specific dependencies here -->
    </dependencies>
    <build>
        <sourceDirectory>src/</sourceDirectory>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <executions>
                    <execution>
                        <id>compile-tools</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <compileSourceRoots>
                                <compileSourceRoot>${project.basedir}/src</compileSourceRoot>
                            </compileSourceRoots>
                            <outputDirectory>${project.basedir}/classes</outputDirectory>
                            <includes>
                                <include>**/*.java</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
